//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Dashboard___Pagina.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infectados
    {
        public int Id { get; set; }
        public System.DateTime FechaDeUltimoEstado { get; set; }
        public int Edad { get; set; }
        public string Sexo { get; set; }
        public string Estado { get; set; }
    }
}
